function [data,data2,vr] = load_vr(exp_name,exp_date,path_names)

% LOAD_VR: Loads data generated by iMRSIV Unity3D experiment.
%
% [data,data2,vr] = LOAD_VR(exp_name,exp_date,path_names)
%
% exp_name      string that is the name of that experiment
% exp_date      date of experiment as a string, in YYYYMMDD format
% path_names    cell array of strings of location of data
%
% data          frame-by-frame data (see vr.si for column labels)
% data2         DAQ data
% vr            data structure
%
% example usage:
% [data,data2,vr] = load_vr('PlayerOne','20231114',{'C:\VRlogs\'});
% plot(data(:,vr.si.t),data(:,vr.si.pz)) % plots position versus time
%
% John Issa, Northwestern University, 2023

%% preliminaries
if ~exist('path_names','var') || isempty(path_names)
    % list in path_names the locations of VRlogs files
    path_names = {'D:\VRlogs\','C:\Users\John\Documents\VRlogs'};
end
if ~exist('exp_date','var') || isempty(exp_date)
    exp_date = datestr(now,'yyyymmdd');
end

%% get full path names

file_name = [exp_name '_' exp_date '*_log1'];

n_path_names = length(path_names);
for i = 1:n_path_names
    dir_root_i = [path_names{i} ];
    dir_info = dir([dir_root_i file_name]);
    if ~isempty(dir_info)
        dnames = dir_info;
        dir_root = dir_root_i;
    end
    
    % also look in subfolder that uses experiment name
    dir_root_i = [path_names{i} exp_name filesep];
    dir_info = dir([dir_root_i file_name]);
    if ~isempty(dir_info)
        dnames = dir_info;
        dir_root = dir_root_i;
    end
end

%% load files
% for now just use first file
name_root = dnames(1).name;
disp(dir_root)
name_root = [dir_root name_root];
name_root2 = [name_root(1:end-1) '2'];
name_root3 = [name_root(1:end-1) '3.txt'];

tic
f = fopen(name_root,'rb');
A = fread(f,'float32');
fclose(f);
toc

tic
f = fopen(name_root2,'rb');
B = fread(f);
fclose(f);
toc

%% load text document
vr = [];
vr.fnames = {name_root, name_root2, name_root3}';
vr.expID=[exp_name '_' exp_date];
f = fopen(name_root3,'r');

b = fgetl(f); c = textscan(b,'%s','Delimiter',';'); c = c{1}; vr.si = c;
b = fgetl(f); c = textscan(b,'%s','Delimiter',';'); c = c{1}; vr.samp_rate = str2double(c{2});
b = fgetl(f); c = textscan(b,'%s','Delimiter',';'); c = c{1}; vr.nlines = str2double(c{2});

vr.reward_times = [];
b = fgetl(f); c = textscan(b,'%s','Delimiter',';'); c = c{1};
if strcmp(c{1},'vs'), vr.vs = str2double(c{2}); b = fgetl(f); else vr.vs = 8; end
while b ~= -1
    c = textscan(b,'%s','Delimiter',';'); c = c{1};
    switch c{3}
        case {'reward delivered', 'reward'}
            vr.reward_times = [vr.reward_times; str2double(c{1}) str2double(c{2})/vr.samp_rate];
    end
    b = fgetl(f); 
end

fclose(f);

n = size(vr.si,1);
data = reshape(A,n,length(A)/n)';

n2 = vr.nlines;
if ~isempty(B)
    data2 = reshape(B,n2,length(B)/n2);
else data2 = [];
end

%% convert si to a better form
if ~isstruct(vr.si)
    L_si = length(vr.si);
    si = [];
    for i = 1:L_si
        si.(vr.si{i}) = i;
    end
    vr.si = si;
end

